### ISSUE TITLE
[Feature] Disable login for all but admins

### ISSUE THREAD

**Issue by scrobbleme** [saintsystems/disable-user-login#4]
It would be nice to have a global option to disable all users, but admins. Even better with a custom message. Or with the option to select roles/users as an allow list instead disallow list.

Background: When migrating a site to another server or doing updates, it would be great to just disable login to avoid changes while working on the site.

**Comment by pcraig3** [comment]
Hi @scrobbleme,

Not sure if you're still looking for this to work, but we are doing something similar to what you're asking for. In our case, [we want to check users who haven't logged in for a while and then deactivate them](https://github.com/cds-snc/gc-articles/blob/b86885bd4cf24c59981635e0a510cbcdd808f879/wordpress/wp-content/mu-plugins/cds-base/classes/Modules/Users/UserLockout.php#L62-L91).

The functionality doesn't really seem central to what this plugin is about, but rather it provides the concept of "enable/disable" and then you can do what you want with it. To disable users, you want to grab the user meta key and then set it to true.

Here's some code that would do what you're asking 

```php
    public function disableUsers(): void
    {
        // get the plugin 
        $loginPlugin = SSDUL();

        // get all user ids
        $users = get_users(array( 'fields' => array( 'id' ) ));
        $user_ids = array_map(function ($users) {
            return $users->id;
        }, $users);

        // remove superadmins
        $user_ids = array_filter(
            $user_ids,
            function ($user_id) {
                return ! is_super_admin($user_id);
            }
        );

        foreach ($user_ids as $user_id) {
          $disabled = true;
          $originally_disabled = get_user_meta($user_id, $loginPlugin->user_meta_key(), true);

          // Update the user's disabled status
          update_user_meta($user_id, $loginPlugin->user_meta_key(), $disabled);

          // Trigger an action when a user's account is enabled
          if (!$originally_disabled) {
            do_action('disable_user_login.user_disabled', $user_id);
          }        
        }
    }
```

Hope that helps!
