### ISSUE TITLE
Create a new "release" tag for version 1.3.2

### ISSUE THREAD

**Issue by pcraig3** [saintsystems/disable-user-login#6]
Hello! 

Thanks very much for merging #5 yesterday. I'd love to pull this version into our repo, but both [wpackagist](https://wpackagist.org/search?q=Disable+User+Login&type=any&search=) and the [Wordpress directory](https://wordpress.org/plugins/disable-user-login/) only have version 1.3.1.

Not totally sure how to increment the version officially, but I'm assuming that it involves creating a new "release" on GitHub. Let me know if it's something I can help with.

**Comment by anderly** [comment]
@pcraig3 yeah, sorry for the delay. Merged it last night and just released.

It should be on wpackagist and wordpress plugin directory now.
