### ISSUE TITLE
Add quick action to disable a user on users table

### ISSUE THREAD

**Issue by Nikschavan** [saintsystems/disable-user-login#9]
For quickly disabling users

![Users ‹ Dev Docs — WordPress 2022-04-20 at 10 43 29 AM](https://user-images.githubusercontent.com/2931091/164155293-18a22367-8052-496e-8625-b6094e8b1418.jpg)

It would also be helpful to add a filter in the users screen to filter disabled users.

**Comment by anderly** [comment]
Closed by [b325918](https://github.com/saintsystems/disable-user-login/commit/b3259182a5e1bf590abf6a5b1c32ab297382014d). Now available in [Release 1.3.4](../releases/tag/1.3.4)
